// Start of french section

export const fr = {
    Sign_Up: {
        Congratulations: 'Toutes nos félicitations!',
        Success_Signup: 'Vous avez réussi à inscrire votre entreprise',
        We_will_send_you_email: 'Nous vous enverrons un e-mail avec plus de détails sur la façon de soumettre votre candidature pour le réseau de connexion des entrepreneurs.',
        Go_To_Home: "Aller à la page d'accueil",
        Email_Confirm_Match: `L'e-mail et l'e-mail de confirmation doivent correspondre.`,
        Company_Name: `Nom de la compagnie`,
        First_Name: `Prénom`,
        Last_Name: `Nom de famille`,
        Email: `Courriel (ce sera votre nom de connexion)`,
        Reenter_Email: `Re-saisir l'e-mail`,
        Country: `Pays`,
        State_Province: `État/Province`,
        Language: `Langue`,
        Are_you_owner: `Êtes-vous propriétaire/principal?`,
        SignUp: `Inscrivez-vous`,
        SignIn: `S'identifier`,
        Cancel: `Annuler`,
        Phone: `Téléphoner`,
        EmailTxt: `E-mail`,
        Please_Contact_US: `Veuillez contacter notre service de recrutement si vous avez des questions concernant le processus de candidature à l'adresse suivante:`,
        Please_Contact_Canada: `Veuillez contacter notre service aux membres si vous avez des questions concernant le processus de demande à l'adresse suivante:`,
    },

    Application_Type: {
        Application_Types: `Types d'application`,
        Select_The_Application_Type: `Sélectionnez le (s) type (s) d'application et le (s) programme (s) pour lesquels vous postulez:`,
        Insurance_Restoration_IR_Tab: `Restauration d'assurance (IR)`,
        Consumer_Home_Improvement: `Amélioration de l'habitat du consommateur (CHI)`,
        Consumer_Insurance_Repair: `Réparation d'assurance à la consommation (CIR)`,
        Wish_For_Financial_Deferral_Option_Process: `Souhaitez-vous utiliser le processus d'option de report financier?`,
        Application_Types_Yes: `Oui`,
        Application_Types_No: `Non`,
        Financial_Deferral_Guidelines: `Lignes directrices sur le report financier`,
        Summary: `Sommaire`,
        Title_financial_deferal: `Le demandeur doit soumettre la demande dûment remplie avec la page de signature numérique exécutée. Un rapport de crédit Experian détaillé sera généré et examiné pour tous les mandants.`,
        Summary_Text_One: `Le candidat doit soumettre la demande dûment remplie avec la page de signature numérique exécutée. Un rapport de crédit Experian détaillé sera généré et examiné pour tous les mandants; tous les mandants doivent recevoir une cote de crédit «faible risque» afin de renoncer à l'exigence relative aux documents financiers complets. Si le (s) rapport (s) de crédit n'atteint pas le seuil de «faible risque», le demandeur sera tenu de fournir les documents financiers complets nécessaires à l'examen des accréditations financières. Les frais de l'option de report financier ne sont pas remboursables.`,
        Summary_Text_Two: `Si vous choisissez de procéder avec l'option de report financier, le demandeur est toujours tenu de fournir les détails de fin d'exercice suivants:`,
        Summary_Text_Three: `Revenu total`,
        Summary_Text_Four: `Dépenses`,
        Summary_Text_Five: `Revenu net`,
        Summary_Text_Six: `L'option de report financier n'est applicable que pendant le processus de demande. Une fois activée sur les programmes de réseau, votre entreprise devra fournir ses informations financières sur une base annuelle.`,
        Summary_Text_Seven: `Cliquez sur «Accepter» pour reconnaître votre acceptation de toutes les conditions énoncées ci-dessus.`,
        Summary_Text_Eight: `Cliquez sur «Annuler» si vous ne souhaitez pas utiliser l'option de report financier.`,
        Application_Types_Cancel: `Annuler`,
        Application_Types_Agree: `Se mettre d'accord`,
        Click_Here_For_Eligible: `Cliquez ici pour voir si vous êtes éligible.`,
        Application_Types_Alert: `Alerte`,
        Please_Select: `Veuillez sélectionner au moins un métier pour les types de candidature sélectionnés.`,
        Please_Add: `Veuillez ajouter au moins un métier pour les types d'application sélectionnés.`,
        Application_Types_OK: `D'accord`,
        Handles_Property: `Gère les travaux de restauration des dommages matériels soumis directement par l'assureur partenaire.`,
        Handles_Holder: `Gère les travaux de rénovation / rénovation demandés directement par le propriétaire / propriétaire.`,
        Handles_Carrier: `Gère les travaux demandés par le propriétaire / propriétaire du bien non soumis par un partenaire de la compagnie d'assurance.`,
        Application_Types_Logout: `Déconnexion`,
        Global_Button_SaveAndNext: `Enregistrer et suivant`,
        Global_Button_Next: `Suivante`,
    },

    Event_Selection_Alert: {
        Recertification_Alert: 'Recertification',
        App_Update_Alert: `Mise à jour de l'application`,
        Application_Correction_Request_Alert: `Demande de correction d'application`,
        Profile_Changes_Correction_Request_Alert: `Demande de correction des changements de profil`,
        App_Update_Correction_Request_Alert: `Demande de correction de mise à jour de l'application`,
        Territory_Coordinator_Correction_Request_Alert: `Demande de correction du coordonnateur de territoire`,
    },

    General_Keys: {
        Toggle_Calender: `Basculer le calendrier`,
        No_Data_Found: `Aucune donnée trouvée`,
        Empty: 'VIDE',
        Items: 'éléments',
        Items_Per_Page: 'objets par page',
        Global_Alert_Data_Unsaved: `Données non enregistrées.`,
        Global_Alert_Data_Unsaved_Stmt: `Voulez-vous vraiment continuer sans enregistrer?`,
        Search: 'Rechercher',
        Home: 'Domicile',
        Logout: 'Se déconnecter',
        General_Yes: 'Oui',
        General_No: 'Non',
        General_Alert: 'Alerte',
        General_Ok: `D'accord`,
        General_Exit: 'Quitter les données enregistrées',
        General_Sure: 'Êtes-vous sûr de vouloir quitter?',
        General_No_Data: `Il n'y a pas de données disponibles.`,
        General_Jump: 'Sauter à',
        General_One_Record: 'Veuillez ajouter au moins un enregistrement.',
        General_No_Record_Available: 'Aucun enregistrement disponible.',
        Recertification: `Recertification`,
        App_Update: `Mise à jour de l'application`,
        App_Update_Correction: `Demande de correction de mise à jour d'application`,
        Territory_Coordinator_Correction_Request: `Demande de correction du coordonnateur de territoire`,
        Application_Correction_Request: `Demande de correction d'application`,
        done_successfully: `fait avec succès.`,
        something_went_wrong: `Un problème est survenu.`,
        Please_save_changes: `Veuillez enregistrer les modifications pour continuer.`,
        dialog_mobile_documentID: `Document #`,
        dialog_mobile_document_name: `Nom du document`,
        dialog_mobile_document_date: `Date de téléchargement`,
        dialog_mobile_document_uploaded: `Document téléchargé par`,
        Valid_Email_Format: `Veuillez saisir un format d'e-mail valide.`,
        Valid_Page_Name: `Veuillez sélectionner un nom de page valide.`,
        Alert: 'Alerte',
        Stay: 'Rester',
        Session_Timeout: 'Expiration de la session',
        Inactivity_line1: 'En raison de votre inactivité, vous serez automatiquement déconnecté',
        Inactivity_line1_2: 'seconde.',
        Inactivity_line2: 'Appuyez sur rester pour continuer à remplir la demande.'
    },

    Company_Info: {
        File_Validation: 'Les fichiers doivent être de type .pdf, .doc, .docx, .xls, .xlsx, .txt, .jpg, .png, .bmp.',
        Company_Information: 'Informations sur la société',
        DBA_Name: 'Nom DBA:',
        Company_Name_Company_Info: 'Nom de la compagnie:',
        Website: 'Site Internet:',
        Bin_Number: 'Numéro BIN:',
        Federal_Tax_ID: `Numéro d'identification fiscale fédérale:`,
        Franchise_Affiliation: 'Affiliation à la franchise:',
        Select_Franchise_Affiliation: `Sélectionner l'affiliation de franchise`,
        Country_Company_Info: 'Pays:',
        XactNet_Address: 'Adresse XactNet:',
        Symbility_ID: 'ID de symboles:',
        if_any: '(le cas échéant):',
        Preferred_Moisture_Data_Software: `Logiciel de données d'humidité préféré:`,
        Select_One: ' (sélectionnez-en un)',
        DryTrack: 'Piste sèche',
        MICA: 'MICA',
        Moisture_Mapper: `Cartographe d'humidité`,
        Supported_Moisture_Data_Software: `Logiciel de données d'humidité pris en charge:`,
        Select_Apply: `(Sélectionnez tout ce qui s'applique)`,
        Supported_DryTrack: 'DryTrack (en)',
        Supporte_MICA: 'MICA',
        Supported_Moisture_Mapper: `Carte d'humidité`,
        Enter_Number: 'Veuillez saisir une valeur comprise entre 0% et 100%.',
        What_Date_Open: 'À quelle date votre entreprise a-t-elle ouvert?:',
        What_Percent: 'Quel % de votre entreprise globale est sous-traitée?:',
        How_Hear_About_Contractor: 'Comment avez-vous entendu parler de Connection Contracteur?:',
        Number_Of_Employees: `Nombre d'employés?:`,
        Employees_Uniform: 'Vos employés portent-ils un uniforme?:',
        Employees_Uniform_Yes: 'Oui',
        Employees_Uniform_No: 'non',
        Carry_ID: `Vos employés portent-ils une pièce d'identité appropriée?:`,
        Carry_ID_Yes: 'Oui',
        Carry_ID_No: 'non',
        Minimum_Statutory: `Votre entreprise satisfait-elle aux exigences légales minimales en matièred'assurance-accidents du travail?:`,
        Minimum_Statutory_Yes: 'Oui',
        Minimum_Statutory_No: 'non',
        Legal_company: `Il s'agit du nom légal de la société que vous souhaitez utiliser pour les transactions commerciales. Ce nom devra être reflété sur les éléments d'accréditation y compris mais sans s'y limiter les assurances les certificats et les addenda.`,
        Repository: 'Dépôt',
        Corporate: 'Entreprise',
        Corporate_Financial: 'Financière',
        Corporate_Licenses: 'Licences',
        Corporate_Location: 'Emplacement',
        Select_files: 'Sélectionnez les fichiers',
        Drop_Your_Files_Here: 'Déposez vos fichiers ici',
        Document_Uploaded_by_Contractor: `Documents téléchargé par l'entrepreneur`,
        Document_Corporate: 'Entreprise',
        Document_Financial: '?nancières',
        Document_Licenses: 'Licences',
        Document_Location: 'Emplacement',
        Documents_uploaded_by_Contractor_Connection: 'Documents téléchargés par Contractor Connection',
        Document_Contractor_Connection_Corporate: 'Entreprise',
        Documents_Contractor_Connection_Network_Communications_Library: 'Bibliothèque de communications réseau',
        Network_Communications_Library: 'Bibliothèque de communications réseau',
        Document_ID: 'ID de document :',
        Name: 'Nom',
        Date: 'Date',
        Uploaded_By: 'Telechargé par',
        No_records_available: 'Aucun enregistrement disponible',
        Items: 'articles',
        Contact_Information: 'Informations de contact',
        Cancel_Company_Info: 'Annuler',
        Save: 'Sauvegarder',
        Back: 'Retour',
        Next: `Suivante`,
        Save_Next: 'Enregistrer et suivant',
        Invalid_Number: 'Numéro invalide',
        Hammer: `Il s'agit du nom légal de la société que vous souhaitez utiliser pour les transactions commerciales. Ce nom devra figurer sur les éléments d'identification, y compris, mais sans s'y limiter, les assurances, les certificats et les addenda.`,
    },

    Job_Volume_Info: {
        Job_Volume_Informations_Page_Header: 'Information sur le volume de travail',
        Current_Year_Breakdown: `Ventilation de l'année en cours`,
        Insurance: 'Assurance',
        Remodeling: 'Remodelage',
        Year: 'Année',
        RES: 'RES%',
        COM: 'COM%',
        Back: 'Retour',
        Job_Volume_Dialog_Edit: 'Éditer',
        Job_Volume_Dialog_Add: 'Ajouter',
        Current_Year: 'Année actuelle',
        Avg_Job_Amount: 'Montant moyen du travail',
        Add_Job_Volume: 'Ajouter un volume de travail',
        Largest_Single_Job: 'Le plus grand emploi unique',
        Add_Job_Volume_Information: 'Ajouter des informations sur le volumede travail',
        Type_Year_In_YYYY_Format: `Tapez l'année au format aaaa`,
        Data_Between_Company_Opening_Date_And_Current_Date: `Veuillez saisir ds données entre la date d'ouverture de l'entreprise et la date actuelle.`,
        Per_Residential_Insurance_Restoration: `% Restauration d'assurance habitation`,
        Per_Commercial_Insurance_Restoration: `% Restauration d'assurance commerciale`,
        Per_Residential_Remodeling: `% Rénovation résidentielle`,
        Per_Commercial_Remodeling: `% Remodelage commercial`,
        $_Largest_Single_Job: `$ Plus grand travail unique`,
        $_Average_Job_Amount: `$ Montant moyen de l'emploi`,
        Job_Volume_Save: `Sauvegarder`,
        Job_Volume_Cancel: `Annuler`,
        Job_Volume_Year_Error: `Les informations saisies concernent l'année cvile en cours. Veuillez soumettre à nouveau les informations sur le volume de vos emplois au début de l'année prochaine. Je vous remercie.`,
        Job_Volume_Year_Hundred: `Les pourcentages de restauration et de rénoation d’assurances doivent être égaux à 100%. Veuillez corriger les pourcentages pour ajouter le volume de cette année. Je vous remercie.`,
        Add_Atleast_One_Record_Warning: `Veuillez ajouter au moins un enregisrement`,
        Items_Per_Page: `objets par page`,
        Job_Volume_Are_You_Sure: `Êtes-vous sûr?`,
        Job_Volume_Recover_Data: `Vous ne pourrez pas récupérer ces données.`,
        Job_Volume_Not_More_Than_Hundred: `La valeur% ne doit pas être supérieure à 100.`,
        Exit_From_Saved_Data: `Quitter les données enregistrées`,
        Add_At_Least_3_Years_Data_Warning: `veuillez ajouter au moins 3 ans de données`,
        Job_Volume_Informations_Back: 'Retour',
        Job_Volume_Informations_Save_Next: 'Enregistrer et suivant',
        Next: `Suivante`,
        Warning: 'Avertissement',
        Access_Denied: 'Accès refusé .',
        Permission: `Vous n'êtes pas autorisé à accéder à la page Job-Volume`,
        One_Record: `Veuillez ajouter au moins un enregistrement.`,
        Please_Add: `S'il-vous-plait ajoutez`,
        Year_Data: `années de données.`,
        Three_Data: `Veuillez ajouter au moins 3 ans de données.`,
        One_Current_Year: `Veuillez ajouter au moins un enregistrement de l'année en cours.`,
        Same_Year_Inserted: `Cette année existe déjà.`,
        Insurance_R: `Assurance (R)`,
        Insurance_C: `Assurance (C)`,
        Remodeling_R: `Remodelage (R)`,
        Remodeling_C: `Remodelage (C)`,
    },

    Reference_Info: {
        References_Header: 'Les références',
        Add_Reference: 'Ajouter des références',
        Ref_Edit: 'Éditer',
        Ref_Add: 'Ajouter',
        Ref_Type: 'Type',
        Ref_Name: 'Nom',
        Ref_Email: 'Email',
        Ref_Phone: 'Téléphone',
        Ref_Company: 'Compagnie',
        Ref_Position: 'Position',
        Ref_Job_Type: `Type d'emploi`,
        Add_Refrences: 'Ajouter Refrences',
        Type_Reference_Name: 'Nom de référence de type',
        Reference_Type: 'Type de référence',
        Reference_Company: 'Compagnie de référence',
        Reference_Position: 'Position de référence',
        Add_References_Phone: 'Ajouter Des références téléphone',
        Add_References_Email: 'Ajouter des références email',
        Additional_Contact_Name: 'Nom de contact supplémentaire',
        Type_of_job: 'Genre de travail',
        Insurance: 'Assurance',
        Commercial: 'Commercial',
        Material_Supply: `l'approvisionnement en matériaux`,
        Residential: 'Résidentiel',
        Please_Enter_Valid_Phone_Number_Format: 'Please Enter Valid Phone Number Format',
        Phone_Number_must_be_at_least_10_characters_long: 'Le numéro de téléphone doit comporter au moins 10 caractères.',
        Subcontractor: 'Sous-traitant',
        Please_provide_three_references: 'Veuillez fournir trois références pour les types de référence suivants:',
        These_references_are_required: `Ces références sont requises avant de passer à l'étape suivante du processus de demande.`,
        Ref_Cancel: 'Annuler',
        Ref_Save: 'Sauvegarder',
        Add_Refrences_Save_Next: 'Enregistrer et suivant',
        Exit_From_Saved_Data: 'Sortie des données enregistrées',
        You_Sure_Want_Exit: 'Tu es sûr de vouloir sortir?',
        Ref_Recover_Data: 'Vous ne pourrez pas récupérer ces données.',
        No: 'Non',
        Yes: 'Oui',
        Alert: 'Alerte',
        Ref_Warning: 'Avertissement',
        References_Thank_You: 'Je vous remercie.',
        Please_Complete_Minimum_Three: 'Veuillez effectuer un minimum de trois réfrences pour chaque type de référence applicable à votre entreprise.',
        Alert_Ok: `D'accord`,
        Items_Per_Page: 'Articles par page',
        Ref_Back: 'Retour',
        Ref_Save_Next: 'Enregistrer et suivant',
        Ref_Success: 'Succès',
        Ref_Data_Saved: 'Données de référence enregistrées.',
        Ref_Permission: `Vous n'avez pas la permission d'accéder à la page de références.`,
        Warning: 'Avertissement',
        Next: `Suivante`,
        Ref_Access: `Accès Refusé.`,
        Valid_Email: `Veuillez saisir un format d'e-mail valide.`,
    },

    Location_Info: {
        Contractor_Locations_Header: 'Informations sur les installations/autres emplacements',
        Please_add_facilIties: `Veuillez ajouter toutes les installations de votre entreprise pour inclure: Espace de bureau, Espace d'entrepôt et Espace d'exposition.`,
        Serial_No: '#',
        Name_Location: 'Nom',
        Street_Address: 'Adresse de rue',
        Location_Name: 'Nom de la localisation',
        City: 'Ville',
        State: 'Etat',
        FacilIty_Type: `Type d'installation`,
        Location_Type_Grid: 'Type de lieu',
        No_Records_Available_Location: 'Aucun enregistrement disponible.',
        Items_Per_Page_Location: 'Article par page',
        Items_Location: 'Articles',
        Do_You_Have_Other_Locations: `Avez-vous d'autres emplacements qui ont postulé ou sont actuellement membres du réseau?:`,
        The_Contractors_Included_Locations_SatellIte: `Les entrepreneurs inclus dans cette liste ont demandé à être membres ou sont membres du réseau de connexion des entrepreneurs. Si l'autre emplacement ne répond pas à ce critère veuillez les énumérer dans la section «Autres emplacements / bureaux satellites».`,
        If_Yes_Please_add: `Si oui, veuillez ajouter l'emplacement à la liste ci-dessus.`,
        Have_Other_Locations_SatellIte_Offices: `Avez-vous d'autres emplacements ou bureaux satellites?:`,
        The_Contractor_Included_List_Previous_Section: `L'entrepreneur inclus dans cette liste n'est pas membre du réseau de connexion d'entrepreneur mais il est affilié à votre entreprise en tant que propriétaire. Si l'autre emplacement a fait une demande ou fait partie du réseau de connexion de l'entrepreneur veuillez les énumérer dans la section précédente`,
        Please_Add_Minimum_One_Location: `Veuillez ajouter au moins un type d'emplacements de bureaux d'entrepôts et de salles d'exposition pour continuer.`,
        Add_Location_Model: `Ajouter un emplacement`,
        Add_Contractor_Location: `Ajouter un emplacement d'entrepreneur`,
        Type_FacilIty_Location_Name: `Type Nom de l'emplacement de l'installation`,
        Use_Physical_Address: `Utiliser l'adresse physique?`,
        Postal_Code: `Code Postal`,
        Location_Type: `Type de lieu`,
        Applied_Active_Other_Location: `Appliqué Actif Autre Lieu`,
        Office_Space: `Espace bureau`,
        Other_FacilIty_Space: `Autre espace d'installation`,
        FacilIty_Type_Model: `Type d'installation`,
        Space_Used: `Espace utilisé`,
        Space_Size: `Taille de l'espace`,
        Own_Lease_NA: `Propre/Bail/NA`,
        Location_Photo_Dropzone: `Lieu Photo Dropzone`,
        Select_files_Location: `Sélectionnez les fichiers`,
        Drop_Your_Files_Here_Location: `Déposez vos fichiers ici`,
        Please_Provide_Six_Picture_descriptive: `Veuillez télécharger jusqu'à six photos montrant les espaces de votre établissement.`,
        Location_Alert_Are_You_Sure_Alert: `Êtes-vous sûr?`,
        Location_Alert_Not_Recover_Data: `Vous ne pourrez pas récupérer ces données.`,
        Location_Alert_Yes: `Oui`,
        Location_Alert_No: `Non`,
        Location_Alert_Access_Denied: `Accès refusé.`,
        Location_Alert_Access_Denied_Stmt: `Vous n'avez pas la permission d'accéder à la page des emplacements des entrepreneurs.`,
        Location_Alert_Applied_Other: `Veuillez ajouter les détails de l'emplacement des emplacements appliqués / autres actifs afin de continuer.`,
        Location_Alert_Satellite_Office: `Veuillez ajouter les détails de l'emplacement du bureau satellite afin de continuer.`,
        Contractor_Locations_Done: `Terminé`,
        Separate_Area_for_Office: `Zone séparée pour le bureau?`,
        Separate_Entrance_for_Office: `Entrée séparée pour le bureau?`,
        Contractor_Locations_Back: `Retour`,
        Contractor_Locations_Save: `Enregistrer et suivant`,
        Contractor_Locations_Cancel: `Annuler`,
        Warning: 'Avertissement',
        Back: 'Retour',
        Save: 'Sauvegarder',
        Add: 'Ajouter',
        Edit: 'Éditer',
        Hammer1: `Les entrepreneurs inclus dans cette liste ont demandé à être membres ou sont membres du réseau Contractor Connection. Si l'autre emplacement ne répond pas à ce critère, veuillez les énumérer dans la section Autres emplacements / bureaux satellites.`,
        Hammer2: `L'entrepreneur inclus dans cette liste ne sont pas membres du réseau Contractor Connection, mais sont affiliés à votre entreprise par propriété. Si l'autre emplacement a postulé ou fait partie du réseau Contractor Connection, veuillez les énumérer dans la section précédente.`,
        Access_Denied: 'Accès refusé .',
        Permission: `Vous n'êtes pas autorisé à accéder à la page Emplacement.`,
        Min_Loc: `Veuillez ajouter au moins un type d'emplacement de bureau, d'entrepôt et de salle d'exposition pour continuer.`,
        Applied: `Veuillez ajouter les détails de l'emplacement des emplacements appliqués / autres actifs afin de continuer.`,
        Satellite: `Veuillez ajouter les détails de l'emplacement du bureau satellite afin de continuer.`,
    },

    Surge_Info: {
        Surge_Header: 'Réponse de surtension/CAT',
        wiling_to_mobilize: `Votre entreprise est-elle disposée à se mobiliser en dehors de votre zone de couverture habituelle?`,
        willing_to_expand: `Votre entreprise est-elle disposée à étendre sa couverture en dehors de votre zone de couverture normale?`,
        minimum_no_of_assignment: `Avez-vous besoin d'un nombre minimum de missions pour vous mobiliser?`,
        how_many_hours: `De combien d'heures votre entreprise a-t-elle besoin avant d'être prête à se mobiliser?`,
        how_many_miles: `À combien de kilomètres de votre emplacement physique êtes-vous prêt à étendre la couverture?`,
        trade_equipped: `Quels métiers êtes-vous équipé pour servir?`,
        willing_to_host: `Êtes-vous prêt à accueillir un autre entrepreneur du réseau si vous êtes dans la zone touchée?`,
        share_resources: `Êtes-vous en mesure de partager des ressources avec les entrepreneurs du réseau dans une zone touchée?`,
        contingency_plan: `Votre entreprise a-t-elle un plan d'urgence si vous vous trouvez dans la zone touchée?`,
        Min: 'Min#:',
        Hours: 'Heures:',
        Miles: 'Miles:',
        Yes: 'Oui',
        No: 'Non',
        Cost: 'Frais',
        Licenseing: 'Licence',
        Others: 'Autres',
        Staff: 'Personnel',
        Volume: 'Le volume',
        Reason: 'Raison:',
        Commercial_Board_Up: 'Conseil commercial vers le haut',
        Commercial_Fire_and_Smoke_Cleaning: `Conseil commercial vers le haut Nettoyage commercial d'incendie et de fumée`,
        Commercial_Roofing: 'Toiture commerciale',
        Residental_Board_Up: 'Conseil Résidentiel Up',
        Residental_Fire_and_Smoke_Cleaning: `Nettoyage résidentiel d'incendie et de fumée`,
        Residental_Mitigation: 'Atténuation résidentielle',
        Residental_Roofing: 'Toiture résidentielle',
        Tree_Removal: `Enlèvement d'arbres`,
        Host_Subcontractor: 'Sous-traitant hôte',
        License_Use: 'Utilisation de la licence',
        Shared_Busniness_Space: `Partagé Espace d'affaire`,
        Equipment: 'Équipement',
        Estimators: 'Estimateurs',
        Laborers_Tech: `Ouvriers / Techniciens`,
        Repository: 'Dépôt',
        Corporate: 'Entreprise',
        Document_Uploaded_by_Contractor: `Documents Téléchargé par l'entrepreneur`,
        Name: 'Nom',
        Date: 'Date',
        Uploaded_By: 'Telechargé Par',
        Cancel: 'Annuler',
        mobilization_text: `Mobilisation: la mobilisation concerne la zone de couverture où votre entreprise délocalise du personnel supplémentaire pour gérer le volume des affectations dans une autre partie du pays. Normalement le volume d'affectation une fois mobilisé est géré par un responsable sur site et non depuis les bureaux de votre entreprise.`,
        expand_coverage_text: `Couverture étendue: La couverture étendue est la zone de couverture que votre entreprise desservira pendant une surtension ou une catastrophe dans ou autour de vos zones de service normales. Normalement le volume d'affectation dans une zone de couverture étendue sera géré depuis les bureaux de votre entreprise.`,
        Save: 'Sauvegarder',
        Access_Denied: `Accès refusé.`,
        Access_Denied_Text: `Vous n'êtes pas autorisé à accéder à la page d'informations sur la réponse aux surtensions.`,
        Save_Next: 'Enregistrer et suivant',
        Back: `Retour`,
    },

    Manage_Surge_Info: {
        Manage_Surge_Response_Licences: 'Gérer les licences de réponse aux surtensions',
        State: 'Etat',
        Required_License: `Licences requises`,
        License_Company_DBA_Name: 'Nom du DBA de la société de licence',
        License: 'Licence #',
        Cancel: 'Annuler',
        Save: 'Sauvegarder',
    },
    Contact_Information: {
        Contact_Information_Page_Header: `Coordonnées`,
        Phone_Numbers_Tab_Header: `Les numéros de téléphone`,
        Phone_Numbers_Tab_Office_Phone_Number: `Numéro de téléphone au bureau:`,
        Phone_Numbers_Tab_Alternate_Contact_Number: `Numéro de contact alternatif:`,
        Phone_Numbers_Tab_Emergency_Phone_Number: `Numéro de téléphone d'urgence:`,
        Phone_Numbers_Tab_Fax_Number: `Numéro de fax:`,
        Emails_Tab_Header: `Emails`,
        Emails_Tab_Emails_Text: `Les courriels fournis sur cet onglet seront utilisés pour les notifications concernant les informations d'identification les notifications/mises à jour du programme et les communications réseau globales. Veuillez inclure uniquement les adresses e-mail que vous souhaitez recevoir ces types de notifications. Je vous remercie.`,
        Emails_Tab_Email_Address: `Adresse e-mail`,
        Valid_Format: `Veuillez saisir un format d'e-mail valide.`,
        Primary_Contact_Tab_Header: `Premier contact`,
        Primary_Contact_Contact_Tab_Name: `Nom du contact:`,
        Primary_Contact_Contact_Tab_Number: `Numéro de contact:`,
        Primary_Contact_Contact_Tab_Email: `Email du contact:`,
        Primary_Training_Contact_Email: `Courriel de contact pour la formation:`,
        Billing_Contact_Tab_Header: `Contact de facturation`,
        Billing_Contact_Tab_Company: `Entreprise:`,
        Billing_Contact_Tab_Contact_Name: `Nom du contact:`,
        Enter_Valid_Name: `Merci d'entrer un nom valide`,
        Contact_Number: `Numéro de contact:`,
        Billing_Contact_Tab_Contact_Phone: `Téléphone de contact:`,
        Billing_Contact_Tab_Contact_Fax: `Contacter Fax:`,
        Billing_Contact_Tab_Contact_Email: `Contacter Email:`,
        Enter_Valid_Format: `Veuillez entrer un format d'e-mail valide`,
        Physical_Address_Tab_Header: `Adresse physique`,
        Physical_Address_Tab_Search_For_Location: `rechercher un lieu`,
        Physical_Address_Tab_Google_Map: `Google Map`,
        Physical_Address_Tab_Street_Address: `Adresse de rue:`,
        Physical_Address_Tab_Street_Address_2: `Adresse civique 2:`,
        Physical_Address_Tab_City: `Ville:`,
        Physical_Address_Tab_State_Province: `État / Province:`,
        Physical_Address_Tab_Postal_Code: `Code postal:`,
        Physical_Address_Tab_Use_as_Mailing_Address: `Utiliser comme adresse postale?:`,
        Physical_Address_Tab_Use_as_Billing_Address: `Utiliser comme adresse de facturation?:`,
        Physical_Address_Tab_Billing_Address_Yes: `Oui`,
        Physical_Address_Tab_Billing_Address_No: `Non`,
        Physical_Address_Tab_Mailing_Address_Yes: `Oui`,
        Physical_Address_Tab_Mailing_Address_No: `Non`,
        Billing_Address_Tab_Header: `Adresse de facturation`,
        Billing_Address_Tab_Search_For_Location: `rechercher un lieu`,
        Billing_Address_Tab_Google_Map: `Google Map`,
        Billing_Address_Tab_Street_Address: `Adresse de rue:`,
        Billing_Address_Tab_Street_Address_2: `Adresse civique 2:`,
        Billing_Address_Tab_City: `Ville:`,
        Billing_Address_Tab_State_Province: `État / Province:`,
        Billing_Address_Tab_Postal_Code: `Code postal:`,
        Mailing_Address_Tab_Header: `Adresse postale`,
        Mailing_Address_Tab_Search_For_Location: `rechercher un lieu`,
        Mailing_Address_Tab_Google_Map: `Google Map`,
        Mailing_Address_Tab_Street_Address: `Adresse de rue:`,
        Mailing_Address_Tab_Street_Address_2: `Adresse civique 2:`,
        Mailing_Address_Tab_City: `Ville:`,
        Mailing_Address_Tab_State_Province: `État / Province:`,
        Mailing_Address_Tab_Postal_Code: `Code postal:`,
        Email_Tab_Back: `Retour`,
        Next: `Suivante`,
        Cancel: `Annuler`,
        Email_Tab_Save: `Enregistrer et suivant`,
        CCC_Contacts_Tab_Back: `Retour`,
        CCC_Contacts_Tab_Save: `Enregistrer et suivant`,
        Billing_Contact_Tab_Back: `Retour`,
        Billing_Contact_Tab_Save: `Enregistrer et suivant`,
        Physical_Address_Tab_Back: `Retour`,
        Physical_Address_Tab_Save: `Enregistrer et suivant`,
        Billing_Address_Tab_Back: `Retour`,
        Billing_Address_Tab_Save: `Enregistrer et suivant`,
        Mailing_Address_Tab_Back: `Retour`,
        Mailing_Address_Tab_Save: `Enregistrer et suivant`,
        Phone_Numbers_Tab_Back: `Retour`,
        Phone_Numbers_Tab_Save: `Enregistrer et suivant`,
        Contact_Info_Alert_Access_Denied: `Accès refusé.`,
        Contact_Info_Alert_Access_Denied_Stmt: `Vous n'avez pas la permission d'accéder à la page d'informations de contact.`,
        Contact_Info_Alert_Data_Unsaved: `Données non enregistrées`,
        Contact_Info_Alert_Data_Unsaved_Stmt: `Veuillez revenir en arrière et enregistrer les modifications si nécessaire.`,
        Alert: `Alerte`,
        Contact_Info_Alert_Duplicate_Email: `Adresse e-mail en double trouvée.`,
        Global_Alert_Header_Warning: `Avertissement`,
        Global_Alert_Data_Unsaved: `Données non enregistrées.`,
        Global_Alert_Data_Unsaved_Stmt: `Voulez-vous vraiment continuer sans enregistrer?`,
        Global_Button_SaveAndNext: `Enregistrer et suivant`,
        Global_Button_Save: `Enregistrer`,
        Incomplete_Data: `Données incomplètes. Veuillez vérifier et remplir tous les champs de`,
        Phone_Tab: `Onglet Numéros de téléphone.`,
        Email_Tab: `Onglet E-mails.`,
        Primary_Contact_Tab: `Onglet Contact principal.`,
        Billing_Contact_Tab: `Onglet Contact de facturation.`,
        Physical_Address_Tab: `Onglet Adresse physique.`,
        Mailing_Address_Tab: `Onglet Adresse postale.`,
        Billing_Address_Tab: `Onglet Adresse de facturation.`,
    },
    Equip_Info: {
        Equipment_Information_Page_Header: `Information sur l'équipement`,
        Automobiles_Own: `Posséder`,
        Automobiles_Lease: `Bail`,
        Are_The_Company_Vehicles_Marked: `Les véhicules de l'entreprise sont-ils marqués?`,
        Yes: `Oui`,
        No: `Non`,
        Back: `Retour`,
        Save_Next: `Enregistrer et suivant`,
        Logout: `Se déconnecter`,
        Equipment_Alert_Access_Denied: `Accès refusé.`,
        Equipment_Alert_Access_Denied_Stmt: `Vous n'avez pas la permission d'accéder à la page d'informations sur l'équipement.`,
        Global_Button_SaveAndNext: `Enregistrer et suivant`,
        Global_Button_Next: `Suivante`,
        Global_Button_Save: `Enregistrer`,
        Global_Button_Back: `Retour`,
        Global_Alert_Header_Warning: `Avertissement`,
        Global_Alert_Data_Unsaved: `Données non enregistrées.`,
        Global_Alert_Data_Unsaved_Stmt: `Voulez-vous vraiment continuer sans enregistrer?`,
    },
    Trade_Info: {
        Residential: `Résidentiel`,
        Commercial: `Commercial`,
        SingleTrade_Tooltip: `Géré indépendamment comme une seule transaction sans frais généraux ni profit.`,
        CS_Tooltip: `Travaux de réparation ou de rénovation d'assurance demandés par le titulaire/propriétaire non soumis par l'assureur partenaire.`,
        Trade: `Commerce`,
        Trade_Information: `Métiers`,
        Program: `Programme`,
        Sub: `%Sous`,
        Single_Trade: `Commerce unique`,
        CS_Trade: `CS Trade`,
        Consumer_Services_Trade: `Commerce des services aux consommateurs`,
        Save: `Sauvegarder`,
        Trade_Information_Back: `Retour`,
        Trade_Information_Save: `Enregistrer et suivant`,
        Global_Button_Next: `Suivante`,
        Alert_Enter_0to100: `Veuillez saisir un pourcentage de 0 à 100.`,
        Alert_Enter_All_Trades: `Veuillez entrer le pourcentage de tous les métiers sélectionnés.`,
        Alert_Save_Data: `Voulez-vous enregistrer les données avant de quitter?`,
        Access_Denied: `Accès refusé.`,
        Access_Denied_Stmt: `Vous n'avez pas la permission d'accéder à la page d'informations commerciales.`,
        Global_Alert_Data_Unsaved_Stmt: `Voulez-vous vraiment continuer sans enregistrer?`,
        SubOut_Reason: `Raison de sous-sortie`,
        SubOut_Comment: `Commentaire de sous-sortie`,
        Warning: `Avertissement`,
    },
    Legal_Item_Information: {
        Page_Header: `Questions juridiques`,
        Litigations_Last_7_Years: `Votre entreprise ou tout autre principe a-t-il été impliqué dans des litiges au cours des 7 dernières années?`,
        Company_Owner_Principal: `Société/Propriétaire/Principal`,
        Legal_Issue_Answer: `Réponse juridique`,
        Details: `Détails`,
        Legal_Issue_File_Details: `Détails du dossier juridique`,
        Contractor: `Entrepreneur`,
        Save_Add_Another: `Enregistrer et ajouter un autre`,
        Add_Another: `Ajouter un autre`,
        Delete: `Supprimer`,
        Litigation_Date: `Date du litige`,
        Opposing_Parties: `Parties opposées`,
        State_Province_Legal: `État/province`,
        County: `Comté `,
        Resolved: `Résolu`,
        Comments: `commentaires`,
        Save_Legal: `Sauvegarder`,
        Principal_Owner: `Principal/Propriétaire`,
        No_Data_Found_Legal: `Aucune donnée trouvée`,
        Exit_From_Saved_Data_Legal: `Sortie des données enregistrées`,
        Are_You_Sure_You_Want_To_Exit: `Tu es sûr de vouloir sortir?`,
        No_Legal: `non`,
        Yes_Legal: `Oui`,
        Alert_Legal: `Alerte`,
        Are_You_Sure_Proceed_Your_Decision: `Etes-vous sûr de poursuivre votre décision?`,
        Alert_No: `non`,
        Alert_Yes: `Oui`,
        Bankruptcy: `Faillite`,
        Company_Principle_Bankruptcy: `Votre entreprise ou un principe quelconque a-t-il déjà déclaré faillite?`,
        Bankruptcy_Save_Add_Another: `Enregistrer et ajouter un autre`,
        Bankruptcy_Delete: `Supprimer`,
        Bankruptcy_Date: `Date de faillite`,
        Type: `Type`,
        Bankruptcy_State_Province: `État/province`,
        Case_Number: `Numéro de cas`,
        Bankruptcy_Discharged: `Faillite libérée`,
        Discharge_Date: `Date de sortie`,
        Discharge_Date_Yes: `Oui`,
        Discharge_Date_No: `Non`,
        Bankruptcy_Save: `Sauvegarder`,
        Bankruptcy_Exit_From_Saved_Data: `Sortie des données enregistrées`,
        Bankruptcy_Are_You_Sure_You_Want_To_Exit: `Tu es sûr de vouloir sortir?`,
        Bankruptcy_No: `non`,
        Bankruptcy_Yes: `Oui`,
        Business_Licenses: `LICENCES BUSINESS`,
        Company_Principle_Business_License: `Votre entreprise ou un principe quelconque a-t-il déjà vu une licence d'entreprise suspendue ou révoquée?`,
        Legal_Save_Add_Another: `Enregistrer et ajouter un autre`,
        Legal_Delete: `Supprimer`,
        Suspension_Revoke_Date: `Date de révocation de la suspension`,
        License_Name: `Nom de la licence`,
        License_Registration: `Licence/Enregistrement #`,
        Legal_State_Province: `État/province`,
        Legal_Save: `Sauvegarder`,
        Reinstated_Date: `Date rétablie`,
        Aliases: `Alias`,
        Alias_Used: `Un principe a-t-il déjà utilisé un pseudonyme?`,
        Aliases_Save_Add_Another: `Enregistrer et ajouter un autre`,
        Aliases_Delete: `Supprimer`,
        Alias_Start_Date: `Date de début d'Alias`,
        Alias_End_Date: `Date de fin d'Alias`,
        Alias_Save: `Sauvegarder`,
        Felonies_Misdemeanors: `FELONIES - MISDEMEANORS`,
        Convicted_Felon: `Un principe a-t-il été reconnu coupable d'un crime?`,
        Felony_Date: `Date`,
        Felony_State_Province: `État/province`,
        Felony_County: `Comté`,
        Felony_Save_Add_Another: `Enregistrer et ajouter un autre`,
        Felony_Delete: `Supprimer`,
        Felony_Save: `Sauvegarder`,
        Select_Felony: `Sélectionnez Felony ou Misdemeanor`,
        Felony: `Crime`,
        Misdemeanor: `Délit`,
        Explanation: `Explication`,
        Felony_Alert: `Alerte`,
        Fenoly_You_Sure_Proceed_Your_Decision: `Etes-vous sûr de poursuivre votre décision?`,
        Felony_No: `non`,
        Felony_Yes: `Oui`,
        Back_Legal: `Retour`,
        Save_Next_Legal: `Enregistrer et suivant`,
        Next: `Suivante`,
        Legal_Info_Alert_Access_Denied: `Accès refusé.`,
        Legal_Info_Alert_Access_Denied_Stmt: `Vous n'avez pas la permission d'accéder à la page Informations légales.`,
        Legal_Info_Alert_Proceed_Decision: `Êtes-vous sûr de prendre votre décision?`,
        Global_Alert_Header_Warning: `avertissement`,
        Inserting_Updating_Entries: `L'insertion / la mise à jour des entrées pour l'entrepreneur actuel est interdite jusqu'à ce que les modifications en attente soient approuvées.`,
        Deleting_Entries: `La suppression des entrées pour l'entrepreneur actuel est interdite jusqu'à ce que les modifications en attente soient approuvées.`,
        Access_Denied: `Vous n'êtes pas autorisé à accéder à la page Informations légales sur les objets.`,
        Legal_Switch_Text: `Veuillez noter que vous devrez peut-être fournir une preuve de décharge. Contractor Connection exige que les faillites commerciales ou personnelles soient libérées pendant au moins 7 ans.`,
    },
    Financial_Information: {
        Financial_Information: `L'information financière`,
        Financial_Summary: `Sommaire financier`,
        Financial_Grid_Header_SNo: `#`,
        Financial_Grid_Header_Year: `Année`,
        Financial_Grid_Header_Total_Revenue: `Chiffre d'affaires total`,
        Financial_Grid_Header_Total_Expenses: `Total des dépenses`,
        Financial_Grid_Header_Net_Income: `Bénéfice net`,
        Financial_Grid_Header_Total_Assets: `Total de l'actif`,
        Financial_Grid_Header_Total_Liabilities: `Total des passifs`,
        Financial_Grid_Header_Long_Term_Debt: `Dette à long terme`,
        Financial_Grid_Header_Equity: `Équité`,
        Financial_Grid_Header_CR: `CR%`,
        Financial_Grid_Header_DTE: `DTE%`,
        Financial_Last_Reviewed_By: `Les données financières ont été examinées pour la dernière fois par`,
        Financial_Button_Review_Financial: `Examiner les finances`,
        Add_Financial_Data: `Ajouter des données financières`,
        Add_Financial_Information: `Ajouter des informations financières`,
        Alert: `Alerte`,
        Data_Between_Company_Opening_Current: `Veuillez saisir les données entre la date d'ouverture de l'entreprise et la date actuelle.`,
        Ok: `D'accord`,
        Type_Financial_Year: `Type Année Financière`,
        Fiscal_Year: `Exercice fiscal?`,
        Yes: `Oui`,
        No: `non`,
        Enter_Fiscal_Year: `Entrez la date de début de l'exercice`,
        Add_Financial_Information_Total_Revenue: `Chiffre d'affaires total`,
        Add_Financial_Information_Total_Expenses: `Total des dépenses`,
        Add_Financial_Information_Net_Income: `Bénéfice net`,
        Add_Financial_Information_Total_Current_Assets: `Total des actifs courants`,
        Add_Financial_Information_Total_Current_Liabilities: `Total des passifs courants`,
        Add_Financial_Information_Long_Term_Debt: `Dette à long terme`,
        Add_Financial_Information_Equity: `Équité`,
        Financial_Document_Dropzone: `Document financier Dropzone`,
        Financial_Document_Dropzone_Text: `Veuillez vous assurer que les titres des documents financiers sont descriptifs et contiennent l'année.`,
        Select_Files: `Sélectionnez les fichiers`,
        Financial_Drop_Your_Files_Here: `Déposez vos fichiers ici.`,
        Financial_Cancel: `Annuler`,
        Financial_Save: `Sauvegarder`,
        Items_Per_Page: `Articles par page`,
        Items: `Articles`,
        Exit_From_Saved_Data: `Sortie des données enregistrées`,
        Are_You_Sure: `Tu es sûr de vouloir sortir ?`,
        Exit_Yes: `Oui`,
        Exit_No: `non`,
        Back: `Retour`,
        Save_Next: `Enregistrer et suivant`,
        Financial_Edit: `Éditer`,
        Financial_Add: `Ajouter`,
        Financial_Alert_Resubmit_Next_Year: `Les informations saisies concernent l'exercice en cours. Veuillez soumettre à nouveau vos informations financières au début de l'année prochaine. Je vous remercie.`,
        Financial_Alert_Access_Denied: `Accès refusé.`,
        Financial_Alert_Access_Denied_Stmt: `Vous n'avez pas la permission d'accéder à la page d'informations financières.`,
        Financial_Alert_Add_One_Record: `Veuillez ajouter au moins un enregistrement.`,
        Financial_Alert_Please_Add: `S'il-vous-plait ajoutez`,
        Financial_Alert_Years_Data: `années de données.`,
        Financial_Alert_Three_Years_Data: `Veuillez ajouter au moins 3 ans de données.`,
        Financial_Alert_Add_Current_Year: `Veuillez ajouter au moins un enregistrement de l'exercice en cours.`,
        Global_Button_Back: `Retour`,
        Global_Button_SaveAndNext: `Enregistrer et suivant`,
        Global_Button_Next: `Suivante`,
        Global_Alert_Are_You_Sure: `Êtes-vous sûr?`,
        Global_Alert_Not_Recover_Data: `Vous ne pourrez pas récupérer ces données.`,
        Global_Alert_Header_Warning: `Avertissement`,
    },
    Language_Veteran: {
        VeteranOwnedBusinessHammerHower: `Définition : Le terme « entreprise détenue par des anciens combattants » désigne une entreprise qui (1) est détenue à au moins 51 % par un ou plusieurs anciens combattants, ou dans le cas d'une entreprise publique, au moins 51 % des actions sont détenues par un ou plus d'anciens combattants et (2) dont la gestion et les opérations commerciales quotidiennes sont contrôlées par un ou plusieurs anciens combattants.`,
        DisabledOwnedBusinessHammerHower: `Définition : Le terme « entreprise détenue par des personnes handicapées » désigne une entreprise qui est (1) détenue à au moins 51 % par une ou plusieurs personnes handicapées, ou dans le cas d'une entreprise publique, au moins 51 % des actions sont détenues par un ou plusieurs personnes handicapées et (2) dont la gestion et les opérations commerciales quotidiennes sont contrôlées par une ou plusieurs personnes handicapées.`,
        WomanOwnedBusinessHammerHower: `Définition : conformément aux directives fédérales, le terme « entreprise détenue par une femme » désigne une entreprise qui est (1) au moins 51 % détenue par une ou plusieurs femmes ou, dans le cas de toute entreprise publique, au moins 51 % des actions est détenue par une ou plusieurs femmes et (2) dont la gestion et les opérations commerciales quotidiennes sont contrôlées par une ou plusieurs femmes.`,
        MinorityOwnedBusinessHammerHower: `Définition : conformément aux directives fédérales, le terme « entreprise appartenant à une minorité » désigne une entreprise qui (1) est détenue à au moins 51 % par un ou plusieurs individus appartenant à une minorité ou, dans le cas d'une entreprise publique, à au moins 51 % des actions est détenue par un ou plusieurs individus minoritaires et (2) dont la gestion et les opérations commerciales quotidiennes sont contrôlées par un ou plusieurs individus minoritaires.`,
        Languages_Veterans_Information: `Langues/Anciens combattants/Informations sur les minorités`,
        Multilingual_Capabilities: `Capacités multilingues`,
        During_Business_Hours: `Pendant les heures d'ouverture`,
        After_Business_Hours: `Après les heures ouvrables`,
        Federal_Guidelines_for_Minority_Contractors: `Lignes directrices fédérales pour les entrepreneurs minoritaires`,
        Minority_Owned_Business: `Entreprise appartenant à une minorité`,
        Woman_Owned_Business: `Entreprise appartenant à des femmes`,
        Veteran_Owned_Business: `Entreprise appartenant à un ancien combattant`,
        Disabled_Owned_Business: `Entreprise appartenant à un handicap`,
        Veteran_Pledge: `Engagement de vétéran`,
        select_atleast_one_language: `* Veuillez sélectionner au moins une langue pendant les heures d'ouverture`,
        Veteran_Pledge_Count: `Nous nous engageons à augmenter le nombre d'employés vétérans actuels`,
        Veteran_Pledge_To: `à`,
        Veteran_Pledge_By: `par`,
        Veteran_Alert_Employee_Greater_Than_Current_Employee: `Le nombre d'employés doit être supérieur à celui des employés actuels.`,
        Veteran_Alert_Fill_Pledge_Required_Fields: `Veuillez remplir les champs obligatoires pour l'engagement de vétéran.`,
        Save_Veterean: `Sauvegarder`,
        Check_Company: `Cochez ici si votre entreprise n'emploie actuellementpas d'anciens combattants militaires et ne prévoit aucune embauche militaire dans un proche avenir.`,
        ownership_status_of_your_company: `Veuillez répondre ci-dessous concernant le statut de propriété minoritaire ou défavorisée de votre entreprise. Aux fins de définition la minorité peut être basée sur le sexe la race ou la religion conformément aux directives fédérales votre réponse est strictement volontaire. Les informations fournies ci-dessous peuvent être utilisées pour la sélection des entrepreneurs dans un programme de sous-traitants mandatés par une minorité. Vous devrez documenter votre déclaration de statut si elle est sélectionnée.`,
        Save_Next_Veteran: `Enregistrer et suivant`,
        Veteran_Alert_Access_Denied: `Accès refusé.`,
        Veteran_Alert_Access_Denied_Stmt: `Vous n'avez pas la permission d'accéder à la page d'information sur les langues et les anciens combattants.`,
        Global_Button_Save: 'Sauvegarder',
        Save_Next: 'Enregistrer et suivant',
        Back: `Retour`,
    },

    Validation_Info: {
        Validation_Page_Header: 'Validation',
        validation_Logout: 'Se déconnecter',
        Validation_Name: 'Nom',
        Validation_Email: 'Email',
        Validation_Phone: 'Téléphone',
        Validation_Role: 'Rôle',
        Validation_Ownership: 'La possession %',
        Please_Validate_Submission: `Veuillez valider l'exactitude des informations ci-dessous avant de passer à la page de signature, au paiement et à la soumission de la demande.`,
        Submission: `Veuillez valider l'exactitude des informations ci-dessous avant de soumettre.`,
        Validation_Owner_Information: 'Informations sur le propriétaire',
        Validation_Items_Per_Page: 'objets par page',
        Company_Information: 'Informations sur la société',
        DBA_Name: 'Nom DBA:',
        Federal_Tax_ID: `Numéro d'identification fiscale fédérale:`,
        Contact_Name: `Nom du contact:`,
        Contact_Phone: `Numéro du contact:`,
        Contact_Email: `Email du contact:`,
        Sno: 'Sl.No :',
        Back: `Retour`,
        Back_Exit: `Quitter les données enregistrées`,
        Back_Exit_Data_Unsaved: `Données non enregistrées. Voulez-vous vraiment continuer sans enregistrer?`,
        Yes: `Oui`,
        No: `Non`,
        Validation_Save_Next: `Enregistrer et suivant`,
        Data_Unsaved: `Données non enregistrées. Voulez-vous vraiment continuer sans enregistrer?`,
        Next: `Suivante`,
        Success: `Succès`,
        Submit: `Soumettre`,
        Invalid_Email_Address: `Veuillez saisir un format d'e-mail valide.`,
    },
    Internal_Landing: {
        Multiple: `PLUSIEURS`,
        Page_Header: `Page de destination interne`,
        Medallion_Apps_Started: `Applications démarrées`,
        Medallion_Apps_Submitted: `Applications soumises`,
        Medallion_App_Updates_Started: `Mises à jour de l'application démarrées`,
        Medallion_App_Updates_Submitted: `Mises à jour de l'application soumises`,
        Medallion_Apps_Coverage_Profile: `Zone de couverture`,
        Grid_Header_Contractor: `Prestataire`,
        Grid_Header_AIS: `AIS`,
        Grid_Header_Change_Date: `Date de modification`,
        Grid_Header_Change_Type: `Changer le type`,
        Grid_Header_State: `Etat`,
        Grid_Header_Start_Date: `Date de début`,
        Grid_Header_Submit_Date: `Date butoire`,

        Grid_Header_Update_Start_Date: `Date de début`,
        Grid_Header_Update_Submit_Date: `Date butoire`,
        Grid_Header_Issue_Date: `Date d'émission`,

        Grid_Header_Next_Follow_Up: `Prochain suivi`,
        Grid_Header_Milestone_Date: `Date de jalon`,
        Grid_Header_Recert_Status: `Statut de recertification`,
        Grid_Header_Rep: `Représentante`,
        Grid_Header_App_Type: `Type d'application`,
        Medallion_Current_Calls: `Appels en cours`,
        Medallion_Recerts: `Recerts`,
        Medallion_Legal_Issues: `Probleme juridique`,
        Medallion_Profile_Changes: `Changements de profil`,
        Alert_Updated: `Mis à jour`,
        Alert_Date_Updated: `La prochaine date de suivi a été mise à jour avec succès.`,
        Grid_Header_Items: `Articles`,
        Contractor_Id: `ID de l'entrepreneur`,
        Status: `Statut`,
        Due_Date: `Date d'échéance`,
        Last_Follow_Up: `Dernier suivi`,
        Deliverable_Dues: `Livrable dû`,
        Grid_Header_Legal_Issue: `Problème légal`,
    },
    Ops_History: {
        Ops_History: `Historique des opérations`,
        Contractor: `Prestataire`,
        Items: `Articles`,
        Change_Date: `Date de modification`,
        Change_Type: `Changer le type`,
        Status: `Statut`,
        Cancel: `Annuler`,
        Close: `Proche`,
        QuickApprove: `Approbation rapide`,
        NoData: `Pas de données disponibles`,
        Disapprove: `Désapprouver`,
    },

    Contaractor_Operation: {
        Contractor_Operations_Page: `Page Opérations de l'entrepreneur`,
        Add_Event: `Ajouter un évènement`,
        Items: `Articles`,
        Contractor_Mgmt_Event: `Événement de gestion de l'entrepreneur:`,
        Event_Group: `Groupe d'événements`,
        Date: `Date`,
        User: `Utilisatrice`,
        Inserted: 'Inséré',
        successfully_Added: `Événement ajouté avec succès.`,
        Correction_Request_Progress: `Demande de correction en cours`,
        Correction_Request_Pending: `Demande de correction en attente`,
        Ops_Disapproved: `Refusé`,
        Ops_Approved: `Approuvé`,
        Ops_Pending: `En attente`,
    },
    Ownership_Info: {
        Placeholder_Ownership_Structure: `Sélectionnez la structure de propriété`,
        Ownership_Information: `Informations sur la propriété`,
        What_Your_Ownership_Structure: `Quelle est votre structure de propriété?:`,
        Select_Ownership_Structure: `Sélectionnez structure de propriété`,
        Years_Months_Company_Has_Under_Ownership: `# d'années mois entreprise a été sous cette propriété:`,
        Year: `Année`,
        Month: `Mois`,
        Owner_Principal_List: `Liste des Propriétaire/Principal`,
        Name_Ownership: `Nom`,
        Email_Ownership: `Email`,
        Phone_Ownership: `Téléphone`,
        Role: `Rôle`,
        Ownership: `Propriété %`,
        Active: `Active`,
        Veteran: `Vétéran`,
        Legal_Flag: `Drapeau légal`,
        No_Records_Available: `Aucun enregistrement disponible`,
        Back_Ownership: `Retour`,
        Save_Next: `Enregistrer et suivant`,
        Save: `Sauvegarder`,
        Next: `Prochaine`,
        Name_is_Required: `*Le nom est requis`,
        Valid_Name: `Entrez un nom valide`,
        Ownership_Exchange_Listing: `Liste exchange:`,
        Ownership_Stock_Symbol: `Symbole de stock:`,
        Ownership_Structure_Being_Changed: `La structure de propriété est en train d'être modifiée. Voulez-vous importer les principes du propriétaire existant?`,
        Add_Owner_Principal: `Ajouter un propriétaire/directeur`,
        Add_New_Owner_Principal: `Ajouter un nouveau Propriétaire/Principal`,
        Edit_Owner_Principal: `Modifier le propriétaire/directeur`,
        Type_Owner_Principal_Full_Legal_Name_Required: `Type Propriétaire/Nom de Principe (Nom légal complet requis)`,
        New_Owner_Role: `Rôle`,
        New_Owner_Email: `Email`,
        New_Owner_Mobile_Phone: `Téléphone mobile`,
        New_Owner_Ssn: `SSN`,
        New_Owner_Driver_Licence: `Permis de conduire #`,
        Date_Of_Birth: `Date de naissance`,
        Date_Of_Birth_Month_Day_Year: `Mois/Jour/Année`,
        Percentage_Of_Ownership: `Pourcentage de propriété`,
        Percentage_Active: 'Active',
        Role_Is_Required: 'Le rôle est requis',
        Email_Required: `Veuillez saisir un format d'e-mail valide.`,
        Military_Affiliation: `Affiliation militaire`,
        Hire_Date: `Date d'embauche`,
        Thank_You: `Merci pour votre service.`,
        Cancel: 'Annuler',
        Same_Email_Id: `Il semble que vous ayez déjà saisi cet identifiant de messagerie. Souhaitez-vous le réimporter?`,
        Access_Denied: 'Accès refusé .',
        Permission: `Vous n'êtes pas autorisé à accéder à la page Ownership`,
        Data_unsaved: `Données non enregistrées. Voulez-vous vraiment continuer sans enregistrer?`,
        Structure: `La structure de propriété est en cours de modification. Voulez-vous importer les propriétaires/principaux existants?`,
        Same_Email: `Un e-mail / nom en double a été saisi.`,
        Duplicate_Email: `L'adresse e-mail saisie existe déjà dans la liste des propriétaires/principaux.`,
        Email_Contractor_Deleted: `L'e-mail saisi est déjà supprimé par l'entrepreneur. Veuillez saisir un autre e-mail.`,
        Wrong: `Un problème est survenu. Veuillez réessayer plus tard.`,
        Update_Info: `Veuillez mettre à jour vos informations en tant que propriétaire/principe en cliquant sur votre nom. Merci.`,
        Percentage_Ownership: `Le pourcentage de propriété sur cette liste doit être égal à 100%.`,
        Warning: 'Avertissement',
        Multiple_Primary_Owner: `Propriétaire principal déjà ajouté. Veuillez sélectionner un autre de rôle.`,
        you_cant_add: `Vous ne pouvez pas ajouter un nouveau propriétaire/principal.`,
        exisiting_already_100: `Le % de propriété existant est déjà de 100.`,
        cant_enter_more_than_100: `Vous ne pouvez pas saisir un pourcentage de propriété supérieur à 100.`,
        Please_Add_Atleast_One_Owner: `Veuillez ajouter au moins un propriétaire principal.`,
        Email_Exist_In_grid: `L'adresse e-mail saisie existe déjà dans la liste des propriétaires/principaux. Voulez-vous importer ?, sinon entrez une adresse e-mail unique.`,
        Deleted_Email_Exist_In_grid: `L'e-mail saisi est déjà supprimé de la liste du propriétaire/principal. Voulez-vous importer? Si non, entrez une adresse e-mail unique.`,
        Primary_Onwer_Exist: `Plus d'un propriétaire principal sélectionné ! Un seul peut être ajouté.`,
        Are_you_sure_to_delete: `Voulez-vous vraiment supprimer les enregistrements?`,
        Please_select_at_least_one_record_to_delete: `Veuillez sélectionner au moins un enregistrement à supprimer.`,
        Please_Enter_atleast_one_employee_record: `Veuillez saisir au moins un enregistrement d'employé.`,
        Delete_Owner: `Propriétaire/Principal supprimé`,
        Deleted_Owner: `Propriétaire supprimé`,
        Recovered_Owner: `Propriétaire récupéré`,
        Valid_Hire_Date: `La date d'embauche doit être postérieure à la date de naissance`,
        event_Mail_duplicate: `L'e-mail existe déjà mais vous êtes connecté à partir d'un autre événement. Donc, impossible de récupérer. Veuillez saisir un identifiant de messagerie unique.`,
        Cannot_delete_due_to_data_dependency: `Impossible de supprimer en raison de la dépendance des données.`,
        Enter_Between_1to100: `Entrez entre 1 et 100`,
        Percentage_Ownership_Required: `Le pourcentage de propriété est requis`,
    },

    Ops_History_Detail: {
        Ops_History_Details: `Détails de l'historique des opérations`,
        Contractor: `Prestataire`,
        Changed_Date: `Date de modification`,
        Items: `Articles`,
        Contractor_Central_Field: `Champ central de l'entrepreneur:`,
        Old_Value: `Ancienne valeur`,
        New_Value: `Nouvelle valeur`,
        Cancel: `Annuler`,
        Approve: `Approuver`,
        QuickApprove: `Approbation rapide`,
        NoData: `Pas de données disponibles`,
        Disapprove: `Désapprouver`,
        Alert_Something_Went_Wrong: `Un problème est survenu. Veuillez réessayer plus tard.`,
    },
    Coverage_Profile: {
        Coverage_Profile_Information_Page_Header: `Couverture du profil`,
        Coverage_Profile_Type: `Type de profil de couverture`,
        Select_Profile: `Veuillez sélectionner un profil que vous souhaitez créer ou modifier :`,
        State_Covered: `État couvert:`,
        Counties_Covered: `Comtés couverts :`,
        Postal_Codes_Covered: `Codes postaux couverts : `,
        Postal_Codes_Not_Covered: `Codes postaux non couverts : `,
        State_Provinces: `ÉTAT(S)/PROVINCE(S)`,
        State_Province: `État/Province`,
        Select_State_Provinces_Services: `Veuillez sélectionner l'État(s)/Province(s) que vous fournissez des services.`,
        State_Provinces_Create: `Créer`,
        State_Provinces_Modify: `Modifier`,
        State_Provinces_Copy: `Copie`,
        State_Provinces_Back: `Retour`,
        State_Provinces_Next: `Suivante`,
        Counties_Regions: `COMTÉS/RÉGIONS`,
        Please_Select_Counties_Regions: `S'il vous plaît sélectionner les comtés/régions que vous fournissez le service.`,
        Counties_Regions_Create: `Créer`,
        Counties_Regions_Modify: `Modifier`,
        Counties_Regions_Copy: ` Copie`,
        Counties_Regions_Back: `Retour`,
        Counties_Regions_Save_Next: `Enregistrer et suivant`,
        Postal_Codes: `CODES POSTAUX`,
        Postal_Codes_Create: `Créer`,
        Postal_Codes_Modify: `Modifier`,
        Postal_Codes_Copy: `Copie`,
        Select_Provided_Details: `Sélectionnez tout ce qui s'applique et fournissez les détails demandés dans les champs requis.`,
        Postal_Codes_Back: `Retour`,
        Postal_Codes_Save_Next: `Enregistrer et suivant`,
        Add_Atleast_One_Record_Warning: `S'il vous plaît ajouter au moins un enregistrement .`,
        Profile_Selection_Dialog_Box: `Cette section de profil vous permet d'identifier votre zone de couverture et de sélectionner les codes d'état et postaux où votre entreprise fournira des services. En sélectionnant votre territoire de couverture  vous déclarez que vous avez les licences d'entreprise et d'entrepreneur requises pour effectuer des travaux dans ce domaine. Vous devez créer un profil général. Ce profil général est votre profil principal qui capturera le territoire de couverture du code postal pour tous vos métiers et programmes. Si vous desservirez le même territoire de couverture pour tous les métiers  alors le seul profil que vous devrez utiliser est le profil général. Si vous choisissez de desservir un territoire de couverture plus ou moins grand pour un commerce spécifique  vous pouvez créer un profil distinct pour ce commerce. Nous exigeons que vous couvriez les codes postaux que vous indiquez sans évaluer de frais supplémentaires. Si ce n'est pas le cas  vous devrez ajuster votre profil de territoire de couverture en conséquence. La seule exception est au profil Catastrophe s'il vous plaît indiquer les domaines que vous envisageriez de fournir de l'aide dans une situation catastrophique. Les modifications apportées à votre territoire de couverture seront soumises aux Services d'adhésion aux fins de traitement et d'approbation. Si vos modifications sont approuvées  vous recevrez une notification d'acceptation. Si vos modifications ne sont pas approuvées  vous serez contacté par un représentant de Contractor Connection. Veuillez noter que l'achèvement d'un changement de profil n'implique pas que vous recevrez une affectation de travail ou que vous serez activé pour un programme. Pour recevoir des affectations  vous devez être sélectionné pour un programme client.`,
        Coverage_Profile_60_Miles_Warning_Message: `Il ya quelques codes postaux qui sont plus de 60 miles de votre emplacement physique en continuant l'enregistrement  vous êtes d'accord que c'est correct. Voulez-vous aller de l'avant?`,
        Saved_Data_Warning: `Sortie des données enregistrées`,
        Handle: `Gère les travaux de rénovation/rénovation demandés directement par le propriétaire/propriétaire.`,
        ST: 'ST',
        Countys: 'Comté/Région',
        Postal: 'Codes Postaux',
        Save: 'Sauvegarder',
        Delete: 'Effacer',
        Add_Contractor_Coverage_Type: `Ajouter un type de couverture de l'entrepreneur`,
        Cov_Name: `Nom de la couverture de l'entrepreneur`,
        Select_Client: `Sélectionnez le client (Si nécessaire)`,
        Select_Division: `Sélectionnez une division (Si nécessaire)`,
        Select_Program: `Sélectionnez un programme (Si nécessaire)`,
        Select_Trade: `Sélectionnez Trade (Si nécessaire)`,
        Reset: 'Réinitialiser',
        Coverage_Copy_Utility: 'Utilitaire de copie de couverture',
        Source_Profile: ' Le profil source à partir duquel vous allez copier est:',
        Please_Choose: 'bail choisissez votre profil de destination ci-dessous et cliquez sur le bouton "Copier le profil".',
        Please_Note: `Notez s'il vous plaît`,
        Notes: `Les modifications apportées à votre zone de couverture, y compris ces copié, seront soumises aux services aux membres pour traitement. Une notification sera envoyée à la ou aux adresses e-mail de votre profil une fois les modifications mises en œuvre. Si vous avez des questions, veuillez contacter votre coordonnateur des services aux membres.`,
        Cancel: 'Annuler',
        Copy_Profile: `Copier le profil`,
        Success: 'Succès',
        Profile_Created: `profil créé avec succès.`,
        Error: `Erreur`,
        Wrong: `Une erreur s'est produite. Impossible de créer un profil pour le moment.`,
        Copy_Profile_Text: `Votre profil a été copié.`,
        Are_You_Sure: `Êtes-vous sûr?`,
        Are_You_Sure_Text: `Vous ne pourrez pas récupérer ce profil.`,
        Deleted: `Supprimé`,
        Deleted_Text: `Votre profil a été supprimé.`,
        Not_Deleted: `Non supprimé`,
        Not_Deleted_Text: `Une erreur s'est produite, votre enregistrement n'est pas supprimé.`,
        Cancelled: `Annulé`,
        Save_Profile: `Votre profil est enregistré :)`,
        Access_Denied: `Accès refusé.`,
        Send_Mail: 'Envoyer un mail',
        Add_New_Profile: `Ajouter un nouveau profil`,
        Warning: `Avertissement`,
        Alert: `Alerte`,
        Sure_Unsaved: `Données non enregistrées. Voulez-vous vraiment continuer sans enregistrer ?`,
        State_Validation: `Veuillez sélectionner au moins un état.`,
        County_Validation: `Veuillez sélectionner au moins un comté correspondant à chaque état sélectionné.`,
        Postal_Validation: `Veuillez sélectionner au moins un code postal correspondant à chaque comté sélectionné.`,
        Postal_Unsaved_Data: `Les modifications apportées ne sont pas enregistrées, souhaitez-vous continuer sans enregistrer?`,
        Profile_Deleted: `Profil supprimé.`,
        Alert_On_Deleted_Profile: `La fonction Créer/Copier ne peut pas être exécutée tant que le profil supprimé n'est pas approuvé/refusé par l'utilisateur interne.`,
        Not_Copied: `Non copié`,
        Not_Copied_Text: `Quelque chose s'est mal passé, votre enregistrement n'est pas copié.`,
        Dropdown_Tooltip: `Vous pouvez sélectionner un profil désactivé une fois les modifications approuvées.`,
    },

    Employee_Info: {
        Employee_Info_Page_Header: `Informations sur l'employé`,
        Employee_Info_Viewing: `Visualisation`,
        Employee_Info_Current_Veteran_Count: `Nombre actuel de vétérans:`,
        Employee_Info_Employee_Listing: `Liste des employés`,
        Employee_Info_Grid_Header_SNo: `#`,
        Employee_Info_Grid_Header_Name: `Nom`,
        Employee_Info_Grid_Header_Email: `Email`,
        Employee_Info_Grid_Header_Phone: `Téléphone`,
        Employee_Info_Grid_Header_Role: `Rôle`,
        Employee_Info_Dialog_Header: `Ajouter un employé`,
        Employee_Info_Dialog_Employee_Name: `Nom de l'employé`,
        Employee_Info_Dialog_Mobile_Phone: `Téléphone portable`,
        Employee_Info_Dialog_Veteran: `Vétéran`,
        Employee_Info_Dialog_Veteran_Stmt: `Merci pour votre engagement à embaucher des anciens combattants.`,
        Employee_Info_Dialog_Military_Affiliation: `Affiliation militaire`,
        Employee_Info_Dialog_Hire_Date: `Date d'embauche`,
        Employee_Info_Dialog_Button_Reset: `Réinitialiser`,
        Employee_Info_Dialog_Button_Save: `Sauvegarder`,
        Employee_Info_Alert_Data_Updated: `Données mises à jour avec succès.`,
        Employee_Info_Alert_Something_Went_Wrong: `Un problème est survenu.`,
        Employee_Info_Alert_Access_Denied: `Accès refusé.`,
        Employee_Info_Alert_Access_Denied_Stmt: `Vous n'avez pas la permission d'accéder à la page d'informations sur les employés.`,
        Employee_Info_Type: `Type d'employé :`,
        Employee_Info_Count: `Compter :`,
        Employee_Info_ID: 'ID',
        Employee_Info_Edit: `Modifier l'employé`,
        Same_Email: `L'e-mail existe déjà`,
        Same_Email_Stmt: 'Veuillez saisir un autre e-mail.',
        Valid_Mail: 'Veuillez saisir une adresse e-mail valide.',

        Emp_Delete_Msg: `Voulez-vous vraiment supprimer les enregistrements?`,
        Emp_Delete_SuccessMsg: `Enregistrement supprimé avec succès.`,
        Emp_Checkbox_Alert: `Vous ne pouvez pas supprimer cet employé tant qu'un nouveau contact principal n'a pas été sélectionné et approuvé.
        Veuillez soumettre votre changement de contact principal à partir de l'onglet Informations de contact, et une fois approuvé, vous pouvez supprimer cet employé.
        Veuillez contacter les Services aux membres si vous avez des questions.`,
        Emp_Pls_Select: `Veuillez sélectionner au moins un enregistrement.`,
        Emp_Delete_head: `Supprimé`,
        Emp_Checkbox_Tooltip_Msg: `Le propriétaire principal, le propriétaire et le principal ne peuvent pas être supprimés.`,
        Emp_Delete_Employee_Button: `Supprimer l'employé`,
    },

    Signature_Info: {
        Signature_Page_Header: `Page de signature`,
        Signature_Page: `PAGE DE SIGNATURE`,
        Please_Read_Sign_Original_Signed_Document: `Veuillez lire  signer et dater que vous comprenez les déclarations suivantes. Tous les propriétaires doivent signer individuellement. Veuillez numériser et envoyer par e-mail le document original signé.`,
        Acknowledgement_Statement: `DÉCLARATION DE REMERCIEMENT`,
        ACKNOWLEDGEMENT_STATEMENT_TEXT1: `Nous, soussignés, accordons par la présente à Crawford Contractor Connection, la permission de faire toutes les demandes de renseignements souhaitées, de commander des rapports de solvabilité et de commander des rapports narratifs sur notre société et chacun des soussignés. Nous, soussignés, accordons par la présente à Crawford Contractor Connection, la permission et l'approbation d'évaluer les informations soumises et de fournir une recommandation globale basée sur les informations. La demande est confidentielle et n'engage en aucune façon Crawford Contractor Connection ou le demandeur soussigné.`,
        ACKNOWLEDGEMENT_STATEMENT_TEXT2: `Nous, soussignés, reconnaissons et attestons que les informations fournies dans cette demande sont vraies, au meilleur de nos connaissances. Nous, soussignés, reconnaissons que toutes les accusations criminelles actuelles ou passées contre le (s) mandant (s) ont été divulguées à Crawford Contractor Connection.`,
        ACKNOWLEDGEMENT_STATEMENT_TEXT3: `Nous, soussignés, convenons par la présente que l'application elle-même est protégée par le droit d'auteur et confidentielle de Crawford Contractor Connection et qu'elle sera protégée en tant que telle. En outre, Crawford Contractor Connection convient que les informations du candidat sont confidentielles pour la candidature et seront protégées par Crawford Contractor Connection, étant entendu, cependant, que Crawford Contractor Connection se réserve le droit de diffuser librement les informations du candidat aux clients de Crawford Contractor Connection sans notification au demandeur.`,
        Financial_Deferral_Option: `OPTION DE REPORT FINANCIER ET INFORMATIONS FINANCIÈRES`,
        Financial_Deferral_Option_And_Financial_Information_Text: `Je certifie / Nous certifions  sous peine de parjure  que les informations financières fournies dans cette demande sont véridiques et correctes  cohérentes avec les états financiers vérifiés et / ou financiers utilisés à des fins de rapport annuel.`,
        Legal_Issues: `PROBLEME JURIDIQUE`,
        Legal_Issues_Text: `Je certifie / Nous certifions  sous peine de parjure  que les questions juridiques fournies dans cette demande sont complètes  vraies et correctes.`,
        Qualification_Statement: `DÉCLARATION DE QUALIFICATION`,
        Qualification_Statement_Text: `Si des employés  des sous-traitants ou des gens de métier sont embauchés pour travailler sur n'importe quel travail assigné à Crawford Contractor Connection  il est de la responsabilité de l'entrepreneur du programme de déterminer s'ils sont pleinement autorisés / certifiés et qualifiés pour effectuer le travail qui leur est assigné. Si des actes répréhensibles  une mauvaise manipulation et / ou une négligence sont causés par l'employé  le sous-traitant ou les gens de métier  c'est l'entrepreneur du programme qui est le seul responsable et doit corriger l'action / le problème dès qu'il est reconnu.`,
        Application_Fee: `FRAIS D'INSCRIPTION`,
        Application_Fee_Text1: `Nous reconnaissons qu'un examen approfondi de tous les documents de candidature soumis aura lieu et que les frais de candidature ne sont pas remboursables.`,
        Application_Fee_Text2: `DOSSIER ÉLECTRONIQUE ET DIVULGATION DE SIGNATURE: De temps à autre, Contractor Connection (nous, notre société ou notre société) peut être tenue par la loi de vous fournir certains avis ou divulgations écrits. Vous trouverez ci-dessous les conditions générales pour vous fournir ces notifications et divulgations par voie électronique. Veuillez lire attentivement les informations ci-dessous, et si vous pouvez accéder à ces informations par voie électronique et accepter ces termes et conditions, veuillez confirmer votre accord en cliquant sur le bouton J'accepte '' au bas de ce document.`,
        Application_Fee_Text3: `RECONNAISSANCE DU PROPRIÉTAIRE et CONSENTEMENT: En cliquant sur le bouton «J'accepte» au bas de ce document, vous confirmez que vous êtes un propriétaire officiel de l'entreprise et que vous consentez à utiliser la signature électronique pour tous les documents de Contractor Connection nécessitant une signature. Ces documents incluent, mais sans s'y limiter, les accords de réseau et / ou les addenda spécifiques au réseau et au client. Vous comprenez que votre signature électronique est juridiquement contraignante, tout comme si vous aviez signé manuellement un document papier.`,
        Application_Fee_Text4: `Tous les avis et divulgations vous seront envoyés par voie électronique. Conformément aux procédures décrites dans les présentes, nous vous fournirons par voie électronique tous les avis, divulgations, autorisations, accusés de réception et autres documents du réseau requis qui doivent être fournis ou mis à votre disposition au cours de notre relation avec vous. Pour réduire le risque que vous ne receviez par inadvertance aucun avis ou divulgation, nous préférons vous fournir tous les avis et divulgations requis par la même méthode et à l'adresse e-mail que vous nous avez fournie..`,
        Application_Fee_Text5: `En saisissant vos initiales ", je confirme que: Je suis propriétaire de l'entreprise; et je peux accéder et lire ce document CONSENTEMENT À LA RÉCEPTION ÉLECTRONIQUE DES DOSSIERS ÉLECTRONIQUES ET DE LA SIGNATURE DIVULGATION; et je peux imprimer sur papier la divulgation ou sauvegarder ou envoyer la divulgation vers un endroit où je peux l'imprimer, pour référence et accès futurs; et je consens à recevoir de Contractor Connection, exclusivement par voie électronique, tous les avis, divulgations, autorisations, accusés de réception et autres documents du réseau qui doivent être fournis ou mis à disposition à moi par Contractor Connection au cours de ma relation avec vous.`,
        Signature_Logout: `Se déconnecter`,
        Acknowledgement_Statement_Text: `Nous soussignés accordons par la présente à Crawford Contractor Connection la permission de faire toutes les demandes souhaitées  de commander des rapports de crédit et des rapports narratifs sur notre société et chacun des soussignés. Nous  soussignés  accordons par la présente à Crawford Contractor Connection la permission et l'approbation d'évaluer les informations soumises et de fournir une recommandation globale basée sur ces informations. La demande est confidentielle et ne lie en aucune façon à Crawford Contractor Connection ou au demandeur soussigné.Nous  soussignés  reconnaissons et attestons que les informations fournies dans cette candidature sont véridiques  au meilleur de nos connaissances. Nous  soussignés  reconnaissons que toutes les accusations criminelles actuelles ou passées contre les principes ont été divulguées à Crawford Contractor Connection.Nous  soussignés  convenons par la présente que l'application elle-même est protégée par des droits d'auteur et confidentielle pour Crawford Contractor Connection et sera protégée en tant que telle. En outre  Crawford Contractor Connection accepte que les informations du demandeur soient confidentielles à la demande et seront protégées par Crawford Contractor Connection étant entendu  cependant  que Crawford Contractor Connection se réserve le droit de diffuser librement les informations du demandeur aux clients de Crawford Contractor Connection sans notification au demandeur.`,
        Owner_Principal: `Propriétaire/Directeur`,
        Certify: `Je certifie que j'ai pris les mesures appropriées pour que les propriétaires/directeurs énumérés ci-dessous soient d'accord avec le contenu de la demande et de la page de signature.`,
        Date_Signed: `Date de signature`,
        Initials: `Initiales`,
        Back: `Retour`,
        Save: `Sauvegarder`,
        Submit: 'Soumettre',
        Please_Enter_Initial: 'Veuillez entrer vos initiales.',
        Access_Denied: 'Accès refusé .',
        Permission: `Vous n'êtes pas autorisé à accéder à la page Signature`,
        Something_wrong: `Quelque chose s'est mal passé.`,
        Please_Contact_Admin: `Veuillez contacter l'administrateur.`,
        Application_Fee_Text6: `Votre signature sera datée une fois enregistrée.`,
    },

    Contractor_Operation: {
        Contractor_Operations_Page: `Page Opérations de l'entrepreneur`,
        Managament: `Événement de gestion de l'entrepreneur`,
        Event_Group: `Groupe d'événements`,
        Date: 'Date',
        User: 'Utilisatrice',
        Add_Event: 'Ajouter un évènement',
        Items: 'Articles',
    },

    Operation_Add_Event: {
        Add_Event: 'Ajouter un évènement',
        Contractor_ID: `ID de l'entrepreneur`,
        Contractor_Name: `Nom de l'entrepreneur`,
        Event_Group: `Groupe d'événements`,
        Event_Type: `Type d'événement`,
        Cancel: 'Annuler',
        Save: 'Sauvegarder',
        Related_Event: `Événement connexe`,
    },

    Pending_Profile: {
        Pending_Profile_Change: 'Changement de profil en attente',
        New_Value: 'Nouvelle valeur',
        Old_Value: 'Valeur précédente',
        Cancel: 'Annuler',
        Save: 'Sauvegarder',
    },
    Search_Contractor: {
        Search_Contractor: 'Rechercher un entrepreneur',
        ContractorID: `ID de l'entrepreneur`,
        Contractor_Name: `Nom de l'entrepreneur`,
        OwnerPrincipal: 'Propriétaire principal',
        City: 'Ville',
        State: 'Etat',
        PostalCode: 'Code postal',
        DM: 'DM',
        XNASymbility_ID: 'ID XNA / Symbility',
        Search_Contractor_btn: 'Rechercher un entrepreneur',
        Reset_Contractor_btn: `Réinitialiser`,
        Enter_one_value_to_search_contractor: '*Entrez au moins une valeur pour rechercher un entrepreneur',
        Contractor: 'Prestataire',
        ST: 'ST',
        City_header: 'Ville',
        PostalCode_header: 'Code postal',
        OwnerPrincipal_header: 'Propriétaire principal',
        DM_header: 'DM',
        XNASymbility_ID_header: 'ID XNA / Symbility',
    },

    Questionnaire: {
        Contractor_Questionnaire: `Page Questionnaire de l'entrepreneur`,
        Please_answer: `Veuillez répondre aux questions suivantes concernant votre entreprise`,
        Has_your_company: `Votre entreprise a-t-elle effectué des réparations sur une maison à valeur nette élevée?`,
        Height_Net_Worth: `Les maisons à valeur nette élevée sont définies comme des maisons d'une valeur de C$750,000+.`,
        Access_Denied: 'Accès refusé.',
        Access_Permission: `Vous n'êtes pas autorisé à accéder à la page Questionnaire.`,
    },

    Reassign_Contractor: {
        Reassign_Contractor_Action: `Réaffecter l'action de l'entrepreneur`,
        Contractor: `Prestataire`,
        Contractor_Recruiter: `Recruteur entrepreneur`,
        Contractor_Coordinator: `Coordinateur des entrepreneurs`,
        Reassign_To: `Réaffecter à`,
        Reassign_Until: `Réaffecter jusqu'à`,
        Cancel: `Annuler`,
        Reassign: `Réaffecter`,
    },

    Event_Selection: {
        Alert: 'Alerte',
        Courtesy_Reminder: 'Ceci est un rappel de courtoisie',
        Your_Company: 'votre entreprise',
        Annual_Recert: 'La recertification annuelle doit être renouvelée',
        Has_Been_Request: 'a été invité à fournir un ',
        During_The: 'Pendant le',
        Contractor_Required: `processus, les entrepreneurs doivent mettre à jour leurs enregistrements de connexion de l'entrepreneur Crawford. Veuillez cliquer dessus`,
        Link: 'lien',
        To_Start: 'pour démarrer le ',
        Process: 'processus',
        Recertification: 'Recertification',
        App_Update: `Mise à jour de l'application`,
        Update_Alert: `Mettre à jour l'alerte`,
        Will_Do_Later: `Fera plus tard`,
        Contractor_Connection_Request: `Contractor Connection a demandé`,
        Correction_Request_Sen1: `aux modifications récentes apportées à votre dossier d'entreprise.`,
        Event_Selection_Header: `Sélection d'événement`,
        Profile_Changes: `Demande de correction des changements de profilt`,
        Application_Change: `Demande de correction d'application`,
        Territiory: `Demande de correction du coordonnateur de territoire`,
    },
    Background_Info: {
        Background_Information: `Informations d'arrière-plan`,
        Viewing: `Visualisation`,
        Last_Background_Audit: `Dernier audit de fond`,
        Audit: `Audit`,
        Background_Addendum: `Contexte Addendu`,
        Employee_Count: `Nombre d'employés`,
        BG_Screening_Exception: `Exception de dépistage BG`,
        Annual_Screening_Audit_Required: `Vérification de sélection annuelle requise`,
        Programs: `Programmes`,
        Sub_contracted_Trades: `Métiers sous-traités`,
        Owners: `Propriétaires`,
        Owner_Name: `Nom`,
        Owner_Email: `Email`,
        Owner_Phone: `Téléphone`,
        Ownership: `La possession %`,
        Save: 'sauver',
    },
    Client_Program_Details: {
        Client_Program_Details: `Détails du programme client`,
        Programs: 'Programmes',
        Xactanalysis_Approval: `Approbation du client d'estimation de Xactanalysis`,
        Xactanalysis_Text: `587 / 5000
        Translation results
        La valeur en dollars de l'approbation du client d'estimation de XactAnalysis représente le seuil dans lequel vos estimations seront automatiquement approuvées par le client (ACA) par XactAnalysis. Les estimations comprenant le codage RFG ou HMR Xactimate ne sont pas éligibles pour l'ACA. Si l'entrepreneur estime que la valeur estimée se situe dans la valeur en dollars « Approbation du client d'estimation XactAnalysis » et qu'elle sera AVA par XactAnalysis, l'entrepreneur est encouragé à discuter de la portée des réparations suggérées et/ou des détails de l'estimation avec le membre. « Approbation du client d'estimation XactAnalysis » s'applique uniquement aux missions d'entrepreneur général.`,
        Cancel: `Annuler`,
        Close: `Fermer`,
        Residential: `Résidentiel`,
        Consumer: `Consommateur`,
        Commercial: `Commercial`,
    },

    Credit_Information: {
        ID: 'ID',
        Viewing: 'Visualisation',
        Credit_Information: 'Informations sur le crédit',
        Report_Date: 'Date du compte rendu',
        Report_Type: 'Type de rapport',
        Payment_Trend: 'Tendance de paiement',
        Trade_Lines: '# de lignes commerciales',
        Highest_Credit: 'Crédit le plus élevé',
        Credit_Score: 'Score de crédit',
        Action_Rating: `Évaluation de l'action`,
        Edit_Credit_Report: 'Ajouter/modifier un rapport de crédit',
        Number_of_Trade_Lines: 'Nombre de lignes commerciales',
        Comments: 'commentaires',
        Credit_Cancel: 'Annuler',
        Credit_Save: 'sauver',
        Add_Credit_Report: 'Ajouter un rapport de crédit',
    },
    Profile_Change: {
        BusinessSubContracted: 'Veuillez saisir une valeur comprise entre 0 et 100.',
    },
    Operation_Correction_Request: {
        Correction_Request: `Demande de correction`,
        Cancel: `Annuler`,
        Save: `Sauvegarder`,
        Ok: `D'accord`,
    },
    CR_Detail: {
        Correction_Request_Details: `Détails de la demande de correction`,
        Close: `Fermer`,
        Click_to_view_correction_request_details: `Cliquez pour afficher les détails de la demande de correction.`,
    },
    Edit_Recertification_Date: {
        Edit_Recertification_Date: `Modifier la date de recertification`,
        Contractor: `Prestataire`,
        Enter_New_Recertification_Date: `Entrez une nouvelle date de recertification`,
        Cancel: `Annuler`,
        Save: `Sauvegarder`,
    },
    Admin: {
        Multi_Location: {
            Admin: 'Administrateur',
            Admin_Header: 'Contractor Central - Administrateur',
            Lead_Subscription_saved: `L'abonnement prospect/enfant a bien été enregistré.`,
            Something_wrong: 'Un problème est survenu.',
            select_lead_child_or_user_right: `Veuillez sélectionner un abonnement Lead / Child ou des droits d'utilisateur.`,
            Success: 'Succès',
            User_ID_already_exist: `L'ID utilisateur existe déjà.`,
            User_Saved: 'ID utilisateur enregistré avec succès.',
            MultiLocation_header: `Vous pouvez soit créer l'abonnement de l'entrepreneur principal à l'entrepreneur enfant à partir de cet onglet, soit attribuer des droits multi-sites à un utilisateur spécifique.`,
            Add_MultiLocation_Rights: 'Gérer les droits multi-sites',
            MultiLocation_Desc:
                "Pour créer un abonnement lead-to-child, saisissez l'ID contractant du contractant principal, saisissez l'ID Contracot des enfants sous-traitants, puis cliquez sur le bouton «Enregistrer».",
            Create_Lead_Child_Subscription: 'Créer un abonnement prospect / enfant',
            Select_Lead_Contractors: "Sélectionnez l'entrepreneur principal",
            Select_Child_Contractors: 'Sélectionner les enfants entrepreneurs',
            User_Right_Desc:
                "Pour attribuer des droits multi-sites, entrez d'abord l'ID utilisateur de la personne à laquelle vous souhaitez accorder l'accès, puis cliquez sur le bouton «Enregistrer».",
            Assign_User_Rights: "Attribuer des droits d'utilisateur",
            Enter_UserID_assign_rights: "Saisissez l'ID utilisateur de la personne à laquelle vous souhaitez attribuer des droits",
            Cancel: 'Annuler',
            Save: 'Sauvegarder',
        },

        Licenses: {
            Liscenses_Header: `Gérer les licences`,
            To_Edit: `Éditer`,
            To_Edit_Stmt: `un nom de licence, sélectionnez un nom de licence dans la liste déroulante, effectuez vos modifications et cliquez sur le bouton "`,
            To_Edit_Save: `Sauvegarder`,
            To_Edit_Button: `" bouton`,
            To_Add: `Ajouter`,
            To_Add_Stmt: `un nouveau nom de licence, entrez le nom et la description de la licence, puis cliquez sur le "`,
            To_Add_Save: `Sauvegarder`,
            To_Add_Button: `" bouton`,
            To_Delete: `Supprimer`,
            To_Delete_Stmt: `une licence, sélectionnez un nom de licence dans la liste déroulante, puis cliquez sur le "`,
            Delete: `effacer`,
            // "Button": `"bouton.`,
            Select_Liscense_Name: `Sélectionnez un nom de licence`,
            Description: `la description`,
            Cancel: `Annuler`,
            // 'Save': `Sauvegarder`,
            Liscence_Type: `Licence`,
            data_exist: `existe déjà.`,
            are_you_sure_delete: `Êtes-vous sûr de vouloir supprimer le licence`,
            deleted: `Supprimé`,
            successfully_deleted: `Supprimé avec succès.`,
            are_you_sure_update: `Êtes-vous sûr de vouloir mettre à jour la licence`,
            Updated: `Mise à jour`,
            updated_successfully: `Mis à jour avec succés.`,
            data_no_exist: `n'existe pas.`,
            Inserted: `Inséré`,
            successfully_Added: `ajouté avec succès.`,
            Add_License: `Ajouter/modifier des licence`,
            Remove_License: `Supprimer les licence`,
            Reset: `Réinitialiser`,

            To: `À`,
            To_add: 'Ajouter',
            To_delete: 'Supprimer',
            Button: 'bouton.',
            edit: `Éditer`,
            or: `ou`,
            Save: 'Sauvegarder',
            trash: 'Déchets',
            To_Edit_Line_1: "Licence, vous devez d'abord sélectionner un nom de licence, puis saisir une nouvelle valeur ou sélectionner une valeur à modifier.",
            To_add_Line_2: `Saisissez une nouvelle valeur dans le champ Nom de la licence, puis cliquez sur le bouton`,
            To_add_Line_2_2: `ou sélectionnez un nom de licence, modifiez le nom ou la description, puis cliquez sur le bouton `,
            To_delete_Line_3: `sélectionnez un nom de licence et cliquez sur le`,
        },

        Equipment: {
            To: `À`,
            To_edit: 'Éditer',
            To_add: 'Ajouter',
            To_delete: 'Supprimer',
            Button: 'bouton.',
            edit: `Éditer`,
            or: `ou`,
            Save: 'Sauvegarder',
            Reset: `Réinitialiser`,
            deleted: `Supprimé`,
            Equip_Type: `Type d'équipement`,
            Equip: `Équipement`,
            icon_title1: `Ajouter/Modifier un type d'équipement`,
            delete_title1: `Supprimer le type d'équipement`,
            icon_title2: `Ajouter/Modifier un équipement`,
            delete_title2: `Supprimer l'équipement`,
            trash: 'Déchets',
            Inserted: `Inséré`,
            Updated: `Actualisé`,
            updated_successfully1: `mis à jour avec succés.`,
            updated_successfully2: `mis à jour avec succés.`,
            please_select_equipment_type: `Veuillez sélectionner un type d'équipement.`,
            successfully_Added1: `ajouté avec succès.`,
            successfully_Added2: `ajouté avec succès.`,
            successfully_deleted1: `supprimé avec succès.`,
            successfully_deleted2: `supprimé avec succès.`,
            insertion_failed: `L'insertion de l'équipement a échoué.`,
            cannot_delete_data: `Impossible de supprimer en raison de données enfant dépendantes.`,
            Select_Equipment_Type: `Sélectionnez un type d'équipement`,
            Select_Equipment: `Sélectionnez un équipement`,
            Equipment_Tab_Header: `Gérer les types d'équipement et l'équipement`,
            To_Edit_Line_1: `Équipement, vous devez d'abord sélectionner un type d'équipement, puis saisir une nouvelle valeur ou sélectionner une valeur à modifier.`,
            To_add_Line_2: `Saisissez une nouvelle valeur dans le champ Type d'équipement, puis cliquez sur le bouton`,
            To_add_Line_2_2: `ou sélectionnez un type d'équipement, modifiez et cliquez sur le `,
            To_delete_Line_3: `sélectionnez un type d'équipement ou un équipement et cliquez sur le`,
            data_no_exist1: `n'existe pas.`,
            data_no_exist2: `n'existe pas.`,
            are_you_sure: `Etes-vous sûr que vous voulez supprimer`,
            data_exist: `existe déjà.`,
            are_you_sure_delete1: `Êtes-vous sûr de vouloir supprimer le type d'équipement`,
            are_you_sure_delete2: `Êtes-vous sûr de vouloir supprimer l'équipement`,
            are_you_sure_update1: `Êtes-vous sûr de vouloir mettre à jour le type d'équipement`,
            are_you_sure_update2: `Êtes-vous sûr de vouloir mettre à jour l'équipement`,
            please_select_equiptype: `Veuillez sélectionner un type d'équipement.`,
        },
        Assign_Required_Liscenses: {
            Assign_Required_Licenses: `Attribuer les licences requises`,
            Assign_License_Select: `Pour attribuer des licences, sélectionnez un état et le nom des licences, puis sélectionnez un ou plusieurs
            programmes et métiers à la licence.`,
            Select_State: `Sélectionnez un état / une province`,
            Select_License_name: `Sélectionnez un nom de licence`,
            Select_Program_to_assign: `Sélectionnez le (s) programme (s) à attribuer`,
            Select_trades_to_assign: `Sélectionnez les métiers à attribuer`,
            Cancel: `Annuler`,
            Save: `Sauvegarder`,
            Inserted: `Inséré`,
            Data_Added_Successfully: `Données ajoutées avec succès.`,
        },
    },
    EmailTemplate: {
        To: 'À',
        Cc: 'Cc',
        Bcc: 'Bcc',
        Subject: 'Le sujet',
        Attachment: 'Attachement',
        Subject_And_Body_Are_Required: 'Le sujet et le corps sont requis.',
        Subject_Is_Required: 'Le sujet est requis.',
        Body_Is_Required: 'Le corps est requis.',
        Enter_Valid_Email_Pattern: "Veuillez saisir un format d'e-mail valide.",
        Enter_Unique_Mail_Addresses: 'Veuillez saisir des adresses e-mail uniques.',
        Specify_Atleast_One_Recipient: "S'il vous plaît spécifiez au moins un destinataire.",
        Mail_Sent_Successfully: 'Courrier envoyé avec succès.',
        Something_Went_Wrong: 'Un problème est survenu.',
        Send_Email: 'E-mail',
        Send: 'Envoyer',
        Report: 'PDF_Rapport.pdf',
    },
    SelectEmailAddress: {
        Email_Address_Selection: "Sélection d'adresse(s) e-mail",
        Select_Email_Address: 'Sélectionnez une ou plusieurs adresses e-mail',
        Select_Mail: 'Envoyer',
        Cancel: 'Annuler',
    },

    Credentialing_Information: {
        Credentialing_Information: "Informations d'identification",
        Insurance: 'Assurance',
        Certificates: 'Certificats',
        Training: 'Formation',
        Technical: 'Technique',
        Licenses: 'Licences',
        Miscellaneous: 'Divers',
        Credential_Items: `Élément d'identification`,
        Insurance_Carrier: `Compagnie d'assurance`,
        Coverage_Amount: 'Montant de la couverture',
        Expiration_Date: `Date d'expiration`,
        Due: 'Dû',
        Action: 'Action',
        State: 'État',
        License_Type: `Type de licence`,
        License_Number: `Numéro de licence`,
        No_Changes_Msg: `Vous n'avez aucune modification à enregistrer.`,
        Certificate_Item: `Élément de certificat`,
        Certificate_Firm: `Cabinet de certification`,
        Credentialing_Date: `Date d'accréditation`,
        Technical_Item: `Article technique`,
        Attendees: `Participants/Participantes`,
        Employee_Training_List: `Liste de formation des employés`,
        Contractor_Employee: `Employé de l'entrepreneur`,
        Title: `Titre`,
        Date_completed: `Rendez-vous complet`,
        Save: `Sauvegarder`,
        Cancel: `Annuler`,
        Vendor: `Vendeur/Vendeuse`,
        Report_Number: `Signaler le numéro`,
        View: `Vue`,
        Training_Tracker: `Suivi de formation`,
        Exist_Duplicate_Enteries: `Veuillez fournir des données valides car des entrées en double existent.`,
        Exist_Invalid_Date: 'Il existe une date invalide.',
        Invalid_Date: 'Veuillez entrer une date valide.',
        Are_You_Sure_To_Delete: `Es-tu sûr? Ces données seront complètement supprimées.`,
        Credential_Alert_Access_Denied: 'Accès refusé.',
        Credential_Alert_Access_Denied_Stmt: `Vous n'êtes pas autorisé à accéder à la page Informations d'identification.`,
    },

    Thank_You_Page: {
        Thank_you_header: `Merci d'avoir postulé à Contractor Connection.`,
        what_to_expect: `À QUOI S'ATTENDRE APRÈS L'APPLICATION`,
        Line1: `Un membre de notre service de recrutement communiquera avec le propriétaire dans un proche avenir.`,
        Line2: `Vous aurez une visite du site de notre partenaire de service, WeGoLook, LLC.`,
        Line3: `Vous recevrez une formation supplémentaire spécifique au(x) métier(s) pour lequel vous avez postulé, une fois sélectionné(e).`,
        Line4: `Des vérifications de crédit seront effectuées pour tous les propriétaires et l'entreprise.`,
        Line5: `Le processus de demande peut être long en fonction de nombreux facteurs, y compris, mais sans s'y limiter, la rapidité avec laquelle vous nous retournez les documents demandés.`,
        For_Question_Contact_USA: `Pour toute question, contactez notre service de recrutement aux e-mails suivants`,
        For_Question_Contact_CANADA: `Pour toute question, contactez nos services aux membres aux e-mails suivants`,
        Insurance_Restoration: `Entrepreneurs en restauration d'assurance`,
        Remodeling_Renovation: `Entrepreneur en rénovation/rénovation`,
        Return_Home: `Retournez à votre écran d'accueil pour modifier davantage votre application.`,
        Email_Sent_Success: `E-mail envoyé avec succès.`,
        Email_Already: `E-mail déjà envoyé.`,
        Success_Alert: 'Succès',
        Alert: `Alerte`,
    },
    MultiCheck_FilterKey: {
        Key_Translated: {
            PastDue: 'En souffrance',
            Yesterday: 'Hier',
            Today: "Aujourd'hui",
            Tomorrow: 'Demain',
            SevenDays: '7-jours',
            ForteenDays: '14-jours',
            ThirtyDays: '30-jours',
            FortyDays: '45-jours',
            SixtyDays: '60-jours',
        },
    },
    DropDown_NoData_Msg: {
        Message: 'AUCUNE DONNÉE DISPONIBLE',
    },
};
